server {
    listen 80;
    server_name 39.105.122.95;
    root /var/www/bfsu-acme;
    location /.well-known/acme-challenge/ { try_files $uri =404; }
    location / { return 503 "BFSU Makers Club is being deployed.\n"; add_header Content-Type text/plain; }
}
